services:
  # --- Base de Datos ---
  db:
    image: postgres:15-alpine
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d inventory_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  # --- Backend (FastAPI) ---
  # --- Backend (FastAPI) ---
  backend:
    build: ./backend
    container_name: inventory_backend
    volumes:
      - ./backend:/app
    # --- CAMBIO IMPORTANTE: Entrar a la carpeta src ---
    working_dir: /app
    # --------------------------------------------------
    ports:
      - "0.0.0.0:8000:8000"
    env_file:
      - .env
    # El comando se mantiene igual, pero ahora se ejecutará DENTRO de src
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    depends_on:
      db:
        condition: service_healthy
  # --- Frontend (React + Vite) ---
  # --- Frontend (React + Vite) ---
  frontend:
    build: ./frontend
    container_name: inventory_frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "0.0.0.0:5173:5173"
    environment:
      - CHOKIDAR_USEPOLLING=true
    # AGREGA ESTA LÍNEA (Fuerza a Vite a aceptar conexiones externas)
    command: npm run dev -- --host 0.0.0.0
    depends_on:
      - backend



volumes:
  postgres_data: